[2025-09-09 15:47:54,149] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-09 16:01:16,965] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-09 16:03:22,643] INFO django.utils.autoreload:265 — /app/backend/settings.py changed, reloading.
[2025-09-09 16:09:50,807] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-09 16:11:41,189] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-09 16:12:09,185] INFO django.utils.autoreload:265 — /app/shop/views.py changed, reloading.
[2025-09-09 16:12:10,529] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-09 16:12:50,427] INFO django.utils.autoreload:265 — /app/users/urls.py changed, reloading.
[2025-09-09 16:12:51,290] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-09 16:14:02,454] INFO django.utils.autoreload:265 — /app/orders/urls.py changed, reloading.
[2025-09-09 16:14:03,370] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-09 16:14:21,923] INFO django.utils.autoreload:265 — /app/orders/urls.py changed, reloading.
[2025-09-09 16:14:22,522] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-09 16:15:03,086] INFO django.utils.autoreload:265 — /app/payments/urls.py changed, reloading.
[2025-09-09 16:15:04,373] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-09 16:35:22,794] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-09 16:37:01,654] INFO django.utils.autoreload:265 — /app/payments/urls.py changed, reloading.
[2025-09-09 16:37:02,646] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-09 16:37:04,603] INFO django.utils.autoreload:265 — /app/payments/urls.py changed, reloading.
[2025-09-09 16:37:05,339] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-09 16:37:15,674] INFO django.utils.autoreload:265 — /app/payments/urls.py changed, reloading.
[2025-09-09 16:37:16,186] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-09 16:40:52,362] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-09 16:41:55,619] INFO django.utils.autoreload:265 — /app/backend/settings.py changed, reloading.
[2025-09-09 16:41:56,743] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-09 16:42:44,481] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-09 16:42:59,204] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-09 16:44:48,488] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-09 16:45:06,219] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-09 16:47:51,486] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-09 16:48:13,429] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-11 15:08:00,120] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-11 15:15:27,435] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-11 15:16:14,804] INFO django.utils.autoreload:265 — /app/shop/urls.py changed, reloading.
[2025-09-11 15:16:15,919] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-11 15:16:22,206] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-11 15:24:55,539] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-11 15:25:06,175] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-11 15:43:17,154] INFO django.utils.autoreload:265 — /app/users/models.py changed, reloading.
[2025-09-11 15:43:17,977] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-11 15:43:21,266] INFO django.utils.autoreload:265 — /app/users/models.py changed, reloading.
[2025-09-11 15:43:21,750] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-11 15:43:23,482] INFO django.utils.autoreload:265 — /app/users/models.py changed, reloading.
[2025-09-11 15:43:24,212] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-11 15:43:27,273] INFO django.utils.autoreload:265 — /app/users/models.py changed, reloading.
[2025-09-11 15:43:27,735] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-11 15:43:28,970] INFO django.utils.autoreload:265 — /app/users/models.py changed, reloading.
[2025-09-11 15:43:29,525] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-11 15:43:32,164] INFO django.utils.autoreload:265 — /app/users/models.py changed, reloading.
[2025-09-11 15:43:32,678] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-11 15:43:33,922] INFO django.utils.autoreload:265 — /app/users/models.py changed, reloading.
[2025-09-11 15:43:34,651] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-11 15:43:36,241] INFO django.utils.autoreload:265 — /app/users/models.py changed, reloading.
[2025-09-11 15:43:36,846] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-11 15:43:40,644] INFO django.utils.autoreload:265 — /app/users/models.py changed, reloading.
[2025-09-11 15:43:41,587] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-11 16:07:52,745] INFO django.utils.autoreload:265 — /app/users/models.py changed, reloading.
[2025-09-11 16:07:53,600] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-11 16:08:01,103] INFO django.utils.autoreload:265 — /app/users/models.py changed, reloading.
[2025-09-11 16:08:01,601] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-11 16:08:04,124] INFO django.utils.autoreload:265 — /app/users/models.py changed, reloading.
[2025-09-11 16:08:04,752] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-11 16:08:08,059] INFO django.utils.autoreload:265 — /app/users/models.py changed, reloading.
[2025-09-11 16:08:08,646] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-11 16:08:18,682] INFO django.utils.autoreload:265 — /app/users/models.py changed, reloading.
[2025-09-11 16:08:19,261] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-11 16:08:35,829] INFO django.utils.autoreload:265 — /app/users/models.py changed, reloading.
[2025-09-11 16:08:36,550] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-11 16:09:09,510] INFO django.utils.autoreload:265 — /app/users/models.py changed, reloading.
[2025-09-11 16:09:10,246] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-11 16:09:47,596] INFO django.utils.autoreload:265 — /app/users/models.py changed, reloading.
[2025-09-11 16:09:48,167] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-11 16:12:07,008] INFO django.utils.autoreload:265 — /app/users/models.py changed, reloading.
[2025-09-11 16:12:07,782] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-11 16:14:53,821] INFO django.utils.autoreload:265 — /app/users/models.py changed, reloading.
[2025-09-11 16:14:54,498] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-11 16:15:38,123] INFO django.utils.autoreload:265 — /app/users/models.py changed, reloading.
[2025-09-11 16:15:38,870] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-11 16:15:51,495] INFO django.utils.autoreload:265 — /app/users/models.py changed, reloading.
[2025-09-11 16:15:52,143] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-11 16:16:16,642] INFO django.utils.autoreload:265 — /app/users/models.py changed, reloading.
[2025-09-11 16:16:17,364] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-11 16:17:24,417] INFO django.utils.autoreload:265 — /app/users/views.py changed, reloading.
[2025-09-11 16:17:25,300] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-11 16:18:35,603] INFO django.utils.autoreload:265 — /app/users/views.py changed, reloading.
[2025-09-11 16:18:36,267] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-11 16:19:17,698] INFO django.utils.autoreload:265 — /app/users/views.py changed, reloading.
[2025-09-11 16:19:18,258] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-11 16:19:39,097] INFO django.utils.autoreload:265 — /app/users/views.py changed, reloading.
[2025-09-11 16:19:39,649] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-11 16:20:02,102] INFO django.utils.autoreload:265 — /app/users/views.py changed, reloading.
[2025-09-11 16:20:02,765] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-11 16:20:14,845] INFO django.utils.autoreload:265 — /app/users/views.py changed, reloading.
[2025-09-11 16:20:15,625] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-11 16:21:25,548] INFO django.utils.autoreload:265 — /app/users/views.py changed, reloading.
[2025-09-11 16:21:26,290] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-11 16:22:51,044] INFO django.utils.autoreload:265 — /app/users/views.py changed, reloading.
[2025-09-11 16:22:51,613] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-11 16:30:59,923] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-11 16:32:10,599] INFO django.utils.autoreload:265 — /app/products/admin.py changed, reloading.
[2025-09-11 16:32:11,029] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-11 16:33:11,929] INFO django.utils.autoreload:265 — /app/products/admin.py changed, reloading.
[2025-09-11 16:33:12,363] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-13 12:42:10,787] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-13 12:42:49,636] INFO django.utils.autoreload:265 — /app/orders/admin.py changed, reloading.
[2025-09-13 12:42:50,030] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-13 12:42:57,633] INFO django.utils.autoreload:265 — /app/products/admin.py changed, reloading.
[2025-09-13 12:42:58,037] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-13 12:45:45,885] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-13 12:48:45,049] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-15 15:00:11,541] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-16 15:28:12,354] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-16 15:28:30,426] INFO django.utils.autoreload:265 — /app/products/urls.py changed, reloading.
[2025-09-16 15:28:31,889] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-16 15:30:50,437] INFO django.utils.autoreload:265 — /app/cart/admin.py changed, reloading.
[2025-09-16 15:30:51,148] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-16 16:18:51,232] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-18 15:03:30,505] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-18 15:03:32,120] WARNING django.request:253 — Not Found: /
[2025-09-18 15:03:32,122] WARNING django.server:213 — "GET / HTTP/1.1" 404 3056
[2025-09-18 15:03:32,939] WARNING django.request:253 — Not Found: /favicon.ico
[2025-09-18 15:03:32,940] WARNING django.server:213 — "GET /favicon.ico HTTP/1.1" 404 3107
[2025-09-18 15:07:23,303] INFO django.utils.autoreload:265 — /app/shop/views.py changed, reloading.
[2025-09-18 15:07:24,570] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-18 15:14:24,928] WARNING django.request:253 — Not Found: /
[2025-09-18 15:14:24,930] WARNING django.server:213 — "GET / HTTP/1.1" 404 3056
[2025-09-18 15:44:16,167] INFO django.utils.autoreload:265 — /app/products/models.py changed, reloading.
[2025-09-18 15:44:17,349] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-18 15:48:14,981] INFO django.utils.autoreload:265 — /app/products/views.py changed, reloading.
[2025-09-18 15:48:16,080] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-18 15:48:38,457] INFO django.utils.autoreload:265 — /app/products/views.py changed, reloading.
[2025-09-18 15:48:39,068] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-18 15:49:10,009] INFO django.utils.autoreload:265 — /app/products/views.py changed, reloading.
[2025-09-18 15:49:10,698] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-18 15:50:44,758] INFO django.utils.autoreload:265 — /app/products/views.py changed, reloading.
[2025-09-18 15:50:45,755] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-18 15:51:32,583] INFO django.utils.autoreload:265 — /app/products/serializers.py changed, reloading.
[2025-09-18 15:51:33,233] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-18 15:52:03,223] INFO django.utils.autoreload:265 — /app/products/serializers.py changed, reloading.
[2025-09-18 15:52:03,835] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-18 15:52:34,769] INFO django.utils.autoreload:265 — /app/products/views.py changed, reloading.
[2025-09-18 15:52:35,309] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-18 15:53:54,102] INFO django.utils.autoreload:265 — /app/products/views.py changed, reloading.
[2025-09-18 15:53:54,673] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-18 15:54:13,518] INFO django.utils.autoreload:265 — /app/products/views.py changed, reloading.
[2025-09-18 15:54:14,486] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-18 15:55:33,188] INFO django.utils.autoreload:265 — /app/products/views.py changed, reloading.
[2025-09-18 15:55:34,088] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-18 15:56:00,946] INFO django.utils.autoreload:265 — /app/products/serializers.py changed, reloading.
[2025-09-18 15:56:01,773] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-18 15:56:24,421] INFO django.utils.autoreload:265 — /app/products/views.py changed, reloading.
[2025-09-18 15:56:25,296] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-18 15:57:40,797] WARNING django.request:253 — Not Found: /
[2025-09-18 15:57:40,798] WARNING django.server:213 — "GET / HTTP/1.1" 404 3056
[2025-09-18 15:57:45,988] INFO django.server:213 — "GET /admin/ HTTP/1.1" 200 13039
[2025-09-18 15:57:46,013] INFO django.server:213 — "GET /static/admin/css/base.css HTTP/1.1" 304 0
[2025-09-18 15:57:46,014] INFO django.server:213 — "GET /static/admin/css/dark_mode.css HTTP/1.1" 304 0
[2025-09-18 15:57:46,015] INFO django.server:213 — "GET /static/admin/js/theme.js HTTP/1.1" 304 0
[2025-09-18 15:57:46,553] INFO django.server:213 — "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
[2025-09-18 15:57:46,553] INFO django.server:213 — "GET /static/admin/css/dashboard.css HTTP/1.1" 304 0
[2025-09-18 15:57:46,554] INFO django.server:213 — "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
[2025-09-18 15:57:46,559] INFO django.server:213 — "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
[2025-09-18 15:57:46,610] INFO django.server:213 — "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
[2025-09-18 15:57:46,610] INFO django.server:213 — "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
[2025-09-18 15:58:03,146] INFO django.server:213 — "GET /admin/products/product/ HTTP/1.1" 200 16998
[2025-09-18 15:58:03,214] INFO django.server:213 — "GET /static/admin/css/changelists.css HTTP/1.1" 200 6878
[2025-09-18 15:58:03,219] INFO django.server:213 — "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
[2025-09-18 15:58:03,402] INFO django.server:213 — "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
[2025-09-18 15:58:03,403] INFO django.server:213 — "GET /static/admin/js/core.js HTTP/1.1" 304 0
[2025-09-18 15:58:03,406] INFO django.server:213 — "GET /static/admin/js/actions.js HTTP/1.1" 304 0
[2025-09-18 15:58:03,426] INFO django.server:213 — "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
[2025-09-18 15:58:03,430] INFO django.server:213 — "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[2025-09-18 15:58:03,431] INFO django.server:213 — "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
[2025-09-18 15:58:03,439] INFO django.server:213 — "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
[2025-09-18 15:58:03,461] WARNING django.request:253 — Not Found: /media/catalog/Screenshot_2025-08-28_190234.png
[2025-09-18 15:58:03,477] INFO django.server:213 — "GET /static/admin/img/icon-no.svg HTTP/1.1" 200 560
[2025-09-18 15:58:03,478] INFO django.server:213 — "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
[2025-09-18 15:58:03,487] WARNING django.server:213 — "GET /media/catalog/Screenshot_2025-08-28_190234.png HTTP/1.1" 404 3212
[2025-09-18 15:58:03,594] INFO django.server:213 — "GET /static/admin/js/filters.js HTTP/1.1" 200 978
[2025-09-18 15:58:03,629] INFO django.server:213 — "GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 304 0
[2025-09-18 15:58:03,633] INFO django.server:213 — "GET /static/admin/img/sorting-icons.svg HTTP/1.1" 200 1097
[2025-09-18 15:58:03,637] INFO django.server:213 — "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
[2025-09-18 15:58:10,424] INFO django.utils.autoreload:265 — /app/products/urls.py changed, reloading.
[2025-09-18 15:58:11,455] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-18 15:58:27,609] INFO django.utils.autoreload:265 — /app/products/views.py changed, reloading.
[2025-09-18 15:58:28,654] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-18 15:58:32,174] WARNING django.request:253 — Not Found: /1
[2025-09-18 15:58:32,176] WARNING django.server:213 — "GET /1 HTTP/1.1" 404 3077
[2025-09-18 15:58:41,792] WARNING django.request:253 — Not Found: /product/1
[2025-09-18 15:58:41,793] WARNING django.server:213 — "GET /product/1 HTTP/1.1" 404 3101
[2025-09-18 15:58:51,189] INFO django.server:213 — "GET /products/1 HTTP/1.1" 301 0
[2025-09-18 15:58:51,285] ERROR django.request:253 — Internal Server Error: /products/1/
[2025-09-18 15:58:51,286] ERROR django.server:213 — "GET /products/1/ HTTP/1.1" 500 6923
[2025-09-18 15:58:51,327] INFO django.server:213 — "GET /static/rest_framework/js/jquery-3.7.1.min.js HTTP/1.1" 304 0
[2025-09-18 15:58:51,343] INFO django.server:213 — "GET /static/rest_framework/css/prettify.css HTTP/1.1" 304 0
[2025-09-18 15:58:51,343] INFO django.server:213 — "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
[2025-09-18 15:58:51,344] INFO django.server:213 — "GET /static/rest_framework/css/default.css HTTP/1.1" 304 0
[2025-09-18 15:58:51,359] INFO django.server:213 — "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
[2025-09-18 15:58:51,370] INFO django.server:213 — "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
[2025-09-18 15:58:51,378] INFO django.server:213 — "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
[2025-09-18 15:58:51,380] INFO django.server:213 — "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
[2025-09-18 15:58:51,381] INFO django.server:213 — "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 304 0
[2025-09-18 15:58:51,382] INFO django.server:213 — "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 304 0
[2025-09-18 15:58:51,385] INFO django.server:213 — "GET /static/rest_framework/js/load-ajax-form.js HTTP/1.1" 304 0
[2025-09-18 15:58:51,507] INFO django.server:213 — "GET /static/rest_framework/img/grid.png HTTP/1.1" 304 0
[2025-09-18 15:58:54,841] ERROR django.request:253 — Internal Server Error: /products/1/
[2025-09-18 15:58:54,842] ERROR django.server:213 — "GET /products/1/ HTTP/1.1" 500 6923
[2025-09-18 15:59:40,596] INFO django.utils.autoreload:265 — /app/products/serializers.py changed, reloading.
[2025-09-18 15:59:41,430] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-18 15:59:50,056] ERROR django.request:253 — Internal Server Error: /products/1/
[2025-09-18 15:59:50,057] ERROR django.server:213 — "GET /products/1/ HTTP/1.1" 500 6923
[2025-09-18 15:59:50,639] INFO django.utils.autoreload:265 — /app/products/views.py changed, reloading.
[2025-09-18 15:59:51,698] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-18 15:59:52,278] ERROR django.request:253 — Internal Server Error: /products/1/
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/renderers.py", line 731, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/renderers.py", line 687, in get_context
    'content': self.get_content(renderer, data, accepted_media_type, renderer_context),
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/renderers.py", line 417, in get_content
    content = renderer.render(data, accepted_media_type, renderer_context)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/renderers.py", line 100, in render
    ret = json.dumps(
          ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 202, in encode
    chunks = list(chunks)
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 432, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/local/lib/python3.12/json/encoder.py", line 406, in _iterencode_dict
    yield from chunks
  File "/usr/local/lib/python3.12/json/encoder.py", line 440, in _iterencode
    yield from _iterencode(o, _current_indent_level)
  File "/usr/local/lib/python3.12/json/encoder.py", line 430, in _iterencode
    yield from _iterencode_list(o, _current_indent_level)
  File "/usr/local/lib/python3.12/json/encoder.py", line 326, in _iterencode_list
    yield from chunks
  File "/usr/local/lib/python3.12/json/encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/utils/encoders.py", line 67, in default
    return super().default(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Product is not JSON serializable
[2025-09-18 15:59:52,281] ERROR django.server:213 — "GET /products/1/ HTTP/1.1" 500 159650
[2025-09-18 16:01:08,289] INFO django.utils.autoreload:265 — /app/products/views.py changed, reloading.
[2025-09-18 16:01:09,290] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-18 16:05:13,143] INFO django.utils.autoreload:265 — /app/products/views.py changed, reloading.
[2025-09-18 16:05:13,861] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-18 16:05:14,615] ERROR django.request:253 — Internal Server Error: /products/1/
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/renderers.py", line 731, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/renderers.py", line 687, in get_context
    'content': self.get_content(renderer, data, accepted_media_type, renderer_context),
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/renderers.py", line 417, in get_content
    content = renderer.render(data, accepted_media_type, renderer_context)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/renderers.py", line 100, in render
    ret = json.dumps(
          ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 202, in encode
    chunks = list(chunks)
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 432, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/local/lib/python3.12/json/encoder.py", line 406, in _iterencode_dict
    yield from chunks
  File "/usr/local/lib/python3.12/json/encoder.py", line 440, in _iterencode
    yield from _iterencode(o, _current_indent_level)
  File "/usr/local/lib/python3.12/json/encoder.py", line 430, in _iterencode
    yield from _iterencode_list(o, _current_indent_level)
  File "/usr/local/lib/python3.12/json/encoder.py", line 326, in _iterencode_list
    yield from chunks
  File "/usr/local/lib/python3.12/json/encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/utils/encoders.py", line 67, in default
    return super().default(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Product is not JSON serializable
[2025-09-18 16:05:14,619] ERROR django.server:213 — "GET /products/1/ HTTP/1.1" 500 159787
[2025-09-18 16:05:15,210] ERROR django.request:253 — Internal Server Error: /products/1/
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/renderers.py", line 731, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/renderers.py", line 687, in get_context
    'content': self.get_content(renderer, data, accepted_media_type, renderer_context),
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/renderers.py", line 417, in get_content
    content = renderer.render(data, accepted_media_type, renderer_context)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/renderers.py", line 100, in render
    ret = json.dumps(
          ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 202, in encode
    chunks = list(chunks)
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 432, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/local/lib/python3.12/json/encoder.py", line 406, in _iterencode_dict
    yield from chunks
  File "/usr/local/lib/python3.12/json/encoder.py", line 440, in _iterencode
    yield from _iterencode(o, _current_indent_level)
  File "/usr/local/lib/python3.12/json/encoder.py", line 430, in _iterencode
    yield from _iterencode_list(o, _current_indent_level)
  File "/usr/local/lib/python3.12/json/encoder.py", line 326, in _iterencode_list
    yield from chunks
  File "/usr/local/lib/python3.12/json/encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/utils/encoders.py", line 67, in default
    return super().default(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Product is not JSON serializable
[2025-09-18 16:05:15,212] ERROR django.server:213 — "GET /products/1/ HTTP/1.1" 500 159787
[2025-09-18 16:05:44,935] INFO django.utils.autoreload:265 — /app/products/views.py changed, reloading.
[2025-09-18 16:05:45,517] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-18 16:09:19,277] INFO django.utils.autoreload:265 — /app/products/views.py changed, reloading.
[2025-09-18 16:09:20,563] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-18 16:09:39,179] INFO django.utils.autoreload:265 — /app/products/views.py changed, reloading.
[2025-09-18 16:09:39,852] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-18 16:09:40,892] ERROR django.request:253 — Internal Server Error: /products/1/
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/renderers.py", line 731, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/renderers.py", line 687, in get_context
    'content': self.get_content(renderer, data, accepted_media_type, renderer_context),
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/renderers.py", line 417, in get_content
    content = renderer.render(data, accepted_media_type, renderer_context)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/renderers.py", line 100, in render
    ret = json.dumps(
          ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 202, in encode
    chunks = list(chunks)
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 432, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/local/lib/python3.12/json/encoder.py", line 406, in _iterencode_dict
    yield from chunks
  File "/usr/local/lib/python3.12/json/encoder.py", line 440, in _iterencode
    yield from _iterencode(o, _current_indent_level)
  File "/usr/local/lib/python3.12/json/encoder.py", line 430, in _iterencode
    yield from _iterencode_list(o, _current_indent_level)
  File "/usr/local/lib/python3.12/json/encoder.py", line 326, in _iterencode_list
    yield from chunks
  File "/usr/local/lib/python3.12/json/encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/utils/encoders.py", line 67, in default
    return super().default(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Product is not JSON serializable
[2025-09-18 16:09:40,894] ERROR django.server:213 — "GET /products/1/ HTTP/1.1" 500 159787
[2025-09-18 16:09:41,490] ERROR django.request:253 — Internal Server Error: /products/1/
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/renderers.py", line 731, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/renderers.py", line 687, in get_context
    'content': self.get_content(renderer, data, accepted_media_type, renderer_context),
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/renderers.py", line 417, in get_content
    content = renderer.render(data, accepted_media_type, renderer_context)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/renderers.py", line 100, in render
    ret = json.dumps(
          ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 202, in encode
    chunks = list(chunks)
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 432, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/local/lib/python3.12/json/encoder.py", line 406, in _iterencode_dict
    yield from chunks
  File "/usr/local/lib/python3.12/json/encoder.py", line 440, in _iterencode
    yield from _iterencode(o, _current_indent_level)
  File "/usr/local/lib/python3.12/json/encoder.py", line 430, in _iterencode
    yield from _iterencode_list(o, _current_indent_level)
  File "/usr/local/lib/python3.12/json/encoder.py", line 326, in _iterencode_list
    yield from chunks
  File "/usr/local/lib/python3.12/json/encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/utils/encoders.py", line 67, in default
    return super().default(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Product is not JSON serializable
[2025-09-18 16:09:41,493] ERROR django.server:213 — "GET /products/1/ HTTP/1.1" 500 159787
[2025-09-18 16:10:10,735] INFO django.utils.autoreload:265 — /app/products/views.py changed, reloading.
[2025-09-18 16:10:11,451] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-18 16:10:58,104] INFO django.utils.autoreload:265 — /app/products/serializers.py changed, reloading.
[2025-09-18 16:10:58,743] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-18 16:11:35,374] INFO django.utils.autoreload:265 — /app/products/views.py changed, reloading.
[2025-09-18 16:11:36,555] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-18 16:11:56,196] INFO django.utils.autoreload:265 — /app/products/views.py changed, reloading.
[2025-09-18 16:11:57,519] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-18 16:13:04,793] INFO django.utils.autoreload:265 — /app/products/views.py changed, reloading.
[2025-09-18 16:13:06,142] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-18 16:13:23,403] INFO django.utils.autoreload:265 — /app/products/serializers.py changed, reloading.
[2025-09-18 16:13:24,577] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-18 16:13:41,606] INFO django.utils.autoreload:265 — /app/products/views.py changed, reloading.
[2025-09-18 16:13:42,409] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-18 16:14:01,289] INFO django.utils.autoreload:265 — /app/products/views.py changed, reloading.
[2025-09-18 16:14:01,873] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-18 16:14:24,723] INFO django.utils.autoreload:265 — /app/products/views.py changed, reloading.
[2025-09-18 16:14:25,478] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-18 16:14:30,820] INFO django.utils.autoreload:265 — /app/products/views.py changed, reloading.
[2025-09-18 16:14:31,576] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-18 16:14:37,687] INFO django.utils.autoreload:265 — /app/products/views.py changed, reloading.
[2025-09-18 16:14:38,578] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-18 16:14:52,125] INFO django.utils.autoreload:265 — /app/products/views.py changed, reloading.
[2025-09-18 16:14:52,824] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-18 16:15:20,621] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-18 16:15:40,332] INFO django.utils.autoreload:265 — /app/products/views.py changed, reloading.
[2025-09-18 16:15:41,138] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-18 16:15:43,426] WARNING django.request:253 — Not Found: /
[2025-09-18 16:15:43,427] WARNING django.server:213 — "GET / HTTP/1.1" 404 3056
[2025-09-18 16:15:45,538] INFO django.server:213 — "GET /admin/ HTTP/1.1" 200 13039
[2025-09-18 16:15:47,198] WARNING django.request:253 — Not Found: /product/1
[2025-09-18 16:15:47,199] WARNING django.server:213 — "GET /product/1 HTTP/1.1" 404 3101
[2025-09-18 16:15:54,404] ERROR django.request:253 — Internal Server Error: /products/1/
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/renderers.py", line 731, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/renderers.py", line 687, in get_context
    'content': self.get_content(renderer, data, accepted_media_type, renderer_context),
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/renderers.py", line 417, in get_content
    content = renderer.render(data, accepted_media_type, renderer_context)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/renderers.py", line 100, in render
    ret = json.dumps(
          ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 202, in encode
    chunks = list(chunks)
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 432, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/local/lib/python3.12/json/encoder.py", line 406, in _iterencode_dict
    yield from chunks
  File "/usr/local/lib/python3.12/json/encoder.py", line 440, in _iterencode
    yield from _iterencode(o, _current_indent_level)
  File "/usr/local/lib/python3.12/json/encoder.py", line 430, in _iterencode
    yield from _iterencode_list(o, _current_indent_level)
  File "/usr/local/lib/python3.12/json/encoder.py", line 326, in _iterencode_list
    yield from chunks
  File "/usr/local/lib/python3.12/json/encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/utils/encoders.py", line 67, in default
    return super().default(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Product is not JSON serializable
[2025-09-18 16:15:54,408] ERROR django.server:213 — "GET /products/1/ HTTP/1.1" 500 159488
[2025-09-18 16:16:09,552] INFO django.utils.autoreload:265 — /app/products/views.py changed, reloading.
[2025-09-18 16:16:10,234] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-18 16:16:11,926] INFO django.utils.autoreload:265 — /app/products/views.py changed, reloading.
[2025-09-18 16:16:12,744] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-18 16:16:17,592] ERROR django.request:253 — Internal Server Error: /products/1/
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/renderers.py", line 731, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/renderers.py", line 687, in get_context
    'content': self.get_content(renderer, data, accepted_media_type, renderer_context),
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/renderers.py", line 417, in get_content
    content = renderer.render(data, accepted_media_type, renderer_context)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/renderers.py", line 100, in render
    ret = json.dumps(
          ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 202, in encode
    chunks = list(chunks)
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 432, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/local/lib/python3.12/json/encoder.py", line 406, in _iterencode_dict
    yield from chunks
  File "/usr/local/lib/python3.12/json/encoder.py", line 440, in _iterencode
    yield from _iterencode(o, _current_indent_level)
  File "/usr/local/lib/python3.12/json/encoder.py", line 430, in _iterencode
    yield from _iterencode_list(o, _current_indent_level)
  File "/usr/local/lib/python3.12/json/encoder.py", line 326, in _iterencode_list
    yield from chunks
  File "/usr/local/lib/python3.12/json/encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/utils/encoders.py", line 67, in default
    return super().default(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Product is not JSON serializable
[2025-09-18 16:16:17,601] ERROR django.server:213 — "GET /products/1/ HTTP/1.1" 500 159625
[2025-09-18 16:16:18,343] INFO django.utils.autoreload:265 — /app/products/serializers.py changed, reloading.
[2025-09-18 16:16:19,015] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-18 16:16:19,726] ERROR django.request:253 — Internal Server Error: /products/1/
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/renderers.py", line 731, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/renderers.py", line 687, in get_context
    'content': self.get_content(renderer, data, accepted_media_type, renderer_context),
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/renderers.py", line 417, in get_content
    content = renderer.render(data, accepted_media_type, renderer_context)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/renderers.py", line 100, in render
    ret = json.dumps(
          ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 202, in encode
    chunks = list(chunks)
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 432, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/local/lib/python3.12/json/encoder.py", line 406, in _iterencode_dict
    yield from chunks
  File "/usr/local/lib/python3.12/json/encoder.py", line 440, in _iterencode
    yield from _iterencode(o, _current_indent_level)
  File "/usr/local/lib/python3.12/json/encoder.py", line 430, in _iterencode
    yield from _iterencode_list(o, _current_indent_level)
  File "/usr/local/lib/python3.12/json/encoder.py", line 326, in _iterencode_list
    yield from chunks
  File "/usr/local/lib/python3.12/json/encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/utils/encoders.py", line 67, in default
    return super().default(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Product is not JSON serializable
[2025-09-18 16:16:19,730] ERROR django.server:213 — "GET /products/1/ HTTP/1.1" 500 159625
